trigger: none

pool: Default

resources:
  pipelines:
    - pipeline: "self-pipe"
      source: "<<CI Pipline Name>>"
      branch: main
  repositories:
    - repository: Template
      type: github
      endpoint: gunnargestsson # Service Connection
      name: gunnargestsson/bcbuildtemplate
      ref: master

variables:
- group: BuildVariables

extends:
  template: /.azureDevOps/CD.yml@Template
  parameters:
    version: "current"
    appVersion: "17.2"
    azureSubscription: ""
    createRuntimePackages: true
    configurationFilePath: '.azureDevOps\build-settings.json'
    releasenoteTemplateFilePath: '.azureDevOps\\pte-prod-releasenote.md'

