trigger: none

pool: Default

resources:
  repositories:
    - repository: Template
      type: github
      endpoint: gunnargestsson # Service Connection
      name: gunnargestsson/bcbuildtemplate
      ref: master

variables:
- group: BuildVariables

extends:
  template: /.azureDevOps/CD.yml@Template
  parameters:
    version: "current"
    appVersion: "17.0"
    azureSubscription: "BC_Production_DevOps"
    configurationFilePath: ".azureDevOps\\pte-prod-settings.json"
    releasenoteTemplateFilePath: ".azureDevOps\\pte-prod-releasenote.md"
    DeployToInstance: $(configuration)
