parameters:
- name: version
  displayName: 'Specify build platform version'
  type: string
  default: "current"
- name: appVersion
  displayName: 'Specify build app version'
  type: string
  default: "18.0"
- name: azureSubscription
  displayName: 'Specify azure subscription name'
  type: string
  default: 'My Azure Service Connection'
- name: createRuntimePackages
  displayName: 'Specify boolean value for runtime package creation'
  type: boolean
  default: True
- name: configurationFilePath
  displayName: 'Specifies the path to the build-settings.json file'
  type: string
  default: '.azureDevOps\build-settings.json'
- name: releasenoteTemplateFilePath
  displayName: 'Specifies the path to the release note template markdown file'
  type: string
  default: ''

stages:
- stage: Deployment
  jobs:
  - job: Build
    timeoutInMinutes: 360
    cancelTimeoutInMinutes: 10
    variables:      
      build.clean: all
      platform: x64
      appBuild: $[counter(variables['appVersion'],0)]
      appRevision: 0
      skipComponentGovernanceDetection: True

    steps:
    - checkout: self
      clean: true
      path: 's'

    - checkout: Template
      clean: false
      path: 's\bcbuildtemplate'

    - task: printAllVariables@1

    - task: PowerShell@2
      displayName: 'Copy Build Template'
      inputs:
        targetType: filePath
        filePath: 'bcbuildtemplate\scripts\Copy-Template.ps1'
        arguments: '-AgentToolsDirectory "$(Agent.ToolsDirectory)"'
        failOnStderr: true

    - task: PowerShell@2
      displayName: 'Reading Settings'
      inputs:
        targetType: filePath
        filePath: 'bcbuildtemplate\scripts\Read-Settings.ps1'
        arguments: '-configurationFilePath "$(Build.Repository.LocalPath)\${{ parameters.configurationFilePath }}" -appVersion "$(resources.pipeline.self-pipe.runName)" -version ${{ parameters.version }} -branchName "$(resources.pipeline.self-pipe.sourceBranch)"'
        failOnStderr: true

    - download: self-pipe
      displayName: 'Download build artifacts'

    - task: PowerShell@2
      displayName: 'Deploy to Environment'
      condition: and(succeeded(),ne(variables['Build.Reason'],'PullRequest'),eq('${{ parameters.version }}','current'))
      inputs:
        targetType: filePath
        filePath: 'bcbuildtemplate\scripts\Deploy-App.ps1'
        arguments: '-configurationFilePath "$(Build.Repository.LocalPath)\${{ parameters.configurationFilePath }}" -artifactsFolder "$(Pipeline.Workspace)/self-pipe/${{ parameters.appVersion }}" -branchName "$(resources.pipeline.self-pipe.sourceBranch)"'
    
- stage: ReleaseNote
  displayName: Release Note
  jobs:
  - job: 'ReleaseNote'
    displayName: Generate Release Note
    steps:
    - task: richardfennellBM.BM-VSTS-XplatGenerateReleaseNotes.XplatGenerate-Release-Notes.XplatGenerateReleaseNotes@3
      displayName: 'Create Release Note'
      condition: ne(${{ parameters.releasenoteTemplateFilePath }},'')
      inputs:
        outputfile: "$(Build.ArtifactStagingDirectory)/releasenote-$(resources.pipeline.self-pipe.runName).html"
        templatefile: "$(Build.Repository.LocalPath)/${{ parameters.releasenoteTemplateFilePath }}"
        checkStage: true
        stopOnRedeploy: false
        getParentsAndChildren: true
        dumpPayloadToConsole: true
        replaceFile: True
        checkForManuallyLinkedWI: True
        stopOnError: true

    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact'
      inputs:
        PathtoPublish: "$(Build.ArtifactStagingDirectory)"
        ArtifactName: "releasenote-$(resources.pipeline.self-pipe.runName).html"
